#! /bin/sh

export GTK_THEME=Adwaita-dark

# Definir o tema do cursor diretamente no bspwmrc (opcional)
export XCURSOR_THEME=OSX-ElCap
export XCURSOR_SIZE=24
export MOZ_GTK_TITLEBAR_DECORATION=system

pgrep -x sxhkd >/dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d . . . . . . . . . .

# bspc config border_width 3
bspc config window_gap 2.2

# ~/.config/polybar/launch.sh
bspc config split_ratio 0.52
# bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config border_width 2.5 # espessura da borda
#bspc config normal_border_color "#44475a"  # cor da borda normal
bspc config normal_border_color "#6d6dc7"  # cor da borda normal
bspc config active_border_color "#6d6dc7"  # cor da janela ativa
bspc config focused_border_color "#d5d5f5" # cor da janela em foco
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=onbsp
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ncspot:ncspot state=floating follow=off rectangle=1000x600+780+420 desktop='^9'

sxhkd &
# picom --config /root/.config/picom/picom.conf &
(sleep 1 && picom --config ~/.config/picom/picom.conf) &
nitrogen --restore &
nm-applet &
polybar &
#ncspot &
# darkman run &
xsetroot -cursor_name left_ptr &

xrandr --output eDP-1 --mode 2560x1440 &
xinput set-prop 15 "libinput Scrolling Pixel Distance" 38 &
xinput set-prop 15 "libinput Natural Scrolling Enabled" 1 &
feh --bg-fill ~/.wallpapers/bridge.png

(
  while ! ping -c1 -W1 8.8.8.8 >/dev/null 2>&1; do sleep 1; done
  kitty --class ncspot --name ncspot -e ncspot
) &
